spring:
  application:
    name: Order Service

  datasource:
    url: jdbc:postgresql://localhost:5433/order-service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: order_service
  flyway:
    schemas: order_service
    default-schema: order_service
    create-schemas: true

  #Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-placed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8085

server:
  port: 8081

service:
  inventory:
    base-url: http://localhost:8082

#Spring Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

#Resilience4j configuration for circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      inventoryServiceCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

  #Resilience4j timer configuration for monitoring
  timelimiter:
    instances:
      inventoryServiceTL:
        timeoutDuration: 3s
        cancelRunningFuture: true

  #Retry configuration for retrying failed calls
  retry:
    instances:
      inventoryServiceRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException